

group_by_length : false
batch_size: 8
n_grad_accumulation: 1
learning_rate : 6e-4
weight_decay: 0.1
adam_beta1: 0.9
adam_beta2: 0.95
gradient_accumulation_steps : 1
nb_steps_tot: 50000
dataloader_num_workers : 1
dataloader_pin_memory : True
dataloader_persistent_workers : True
label_smoothing_factor : 0
max_length : 1024
scheduler_name : 'cosine'
warmup : 1000
use_mixed_precision: True
n_warmup_steps: 1000
run_baseline_ddp: False # load model in float32 for ddp
method_name: 'dpu'
eval: False
save: True
eval_step: 500
run_expe_slow: False
const_len_batch: True # set to false for finetuning
finetune: False